baseurl: "/"
languageCode: "en-us"
title: "Shin"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Subscribe
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "[Github](https://github.com/sarckk)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
